version: '3.2'

services:
  ml-workspace:
    image: imansour/ml-workspace-minimal
    restart: always
    volumes:
      - ml-workspace:/workspace
    ports:
      - 8080:8080

volumes:
  ml-workspace: